<?php
require dirname(__DIR__) . '/src/render.php';
page_start('privacidad'); ?>
<section class="page-hero"><div class="shell narrow"><p class="eyebrow">Datos mínimos y uso limitado</p><h1>Privacidad</h1><p class="lede">Cómo tratamos el contacto y el contexto comercial que decidís compartir.</p></div></section><section class="section"><div class="shell prose narrow">
<h2>Responsable y finalidad</h2><p>El canal de solicitudes se habilita después de configurar la identidad de quien lo recibe y la entrega al sistema de gestión. El nombre del responsable aparece junto al botón de envío. Usamos los datos para responder y orientar la solicitud; no para enviar publicidad.</p>
<h2>Qué recibimos</h2><p>Nombre, teléfono, correo opcional, tipo y tamaño de empresa, necesidad y consentimiento. No solicitamos archivos, contraseñas, claves, dominios, IP ni relatos técnicos. No compartimos tu contacto con un especialista sin acordarlo con vos.</p>
<h2>Entrega y conservación</h2><p>La solicitud se registra primero en un archivo privado fuera del directorio público y se intenta entregar al sistema de gestión configurado. La copia local se elimina cuando cumple 30 días: se revisa en cada envío y mediante la tarea diaria de mantenimiento. El sistema de gestión necesita su propia política de conservación y eliminación antes de habilitar el canal.</p>
<h2>Cookies y registros</h2><p>Usamos una cookie de seguridad de sesión en páginas de formulario. La atribución de campañas guarda parámetros de campaña en una cookie propia durante un máximo de 90 días cuando están presentes. La referencia de origen conserva solo el dominio, sin ruta ni parámetros. No cargamos analítica de terceros por defecto. Los registros operativos contienen códigos de resultado; los límites de envío usan identificadores hash de IP.</p>
<h2>Acceso, corrección y eliminación</h2><p>El acceso se limita a personas autorizadas. Usá el <a href="/contacto/">contacto general</a> y elegí el motivo de privacidad. No envíes documentos de identidad por el formulario. El responsable confirmará un canal adecuado si necesita verificar tu solicitud.</p>
<h2>Revisión de este texto</h2><p>Actualización editorial: 5 de octubre de 2026. La identidad legal, los proveedores de tratamiento y la política del sistema de gestión deben completarse y revisarse antes de habilitar solicitudes comerciales.</p>
</div></section><?php page_end(); ?>
